classDiagram
    class Subscription {
        +UUID id
        +String fullName
        +String email
        +String planName
        +Float planPrice
        +DateTime createdAt
    }
    
    class Admin {
        +int id
        +String email
        +String password
    }
